#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAWNProject
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
using System.IO;
using System.IO.IsolatedStorage;
using Microsoft.Phone.Data.Linq.Mapping;
using Microsoft.Phone.Data.Linq;


public class DebugWriter : TextWriter
{
    private const int DefaultBufferSize = 256;
    private System.Text.StringBuilder _buffer;

    public DebugWriter()
    {
        BufferSize = 256;
        _buffer = new System.Text.StringBuilder(BufferSize);
    }

    public int BufferSize
    {
        get;
        private set;
    }

    public override System.Text.Encoding Encoding
    {
        get { return System.Text.Encoding.UTF8; }
    }

    #region StreamWriter Overrides
    public override void Write(char value)
    {
        _buffer.Append(value);
        if (_buffer.Length >= BufferSize)
            Flush();
    }

    public override void WriteLine(string value)
    {
        Flush();

        using(var reader = new StringReader(value))
        {
            string line; 
            while( null != (line = reader.ReadLine()))
                System.Diagnostics.Debug.WriteLine(line);
        }
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
            Flush();
    }

    public override void Flush()
    {
        if (_buffer.Length > 0)
        {
            System.Diagnostics.Debug.WriteLine(_buffer);
            _buffer.Clear();
        }
    }
    #endregion
}


	public partial class DBSoalContext : System.Data.Linq.DataContext
	{
		
		public bool CreateIfNotExists()
		{
			bool created = false;
			if (!this.DatabaseExists())
			{
				string[] names = this.GetType().Assembly.GetManifestResourceNames();
				string name = names.Where(n => n.EndsWith(FileName)).FirstOrDefault();
				if (name != null)
				{
					using (Stream resourceStream = Assembly.GetExecutingAssembly().GetManifestResourceStream(name))
					{
						if (resourceStream != null)
						{
							using (IsolatedStorageFile myIsolatedStorage = IsolatedStorageFile.GetUserStoreForApplication())
							{
								using (IsolatedStorageFileStream fileStream = new IsolatedStorageFileStream(FileName, FileMode.Create, myIsolatedStorage))
								{
									using (BinaryWriter writer = new BinaryWriter(fileStream))
									{
										long length = resourceStream.Length;
										byte[] buffer = new byte[32];
										int readCount = 0;
										using (BinaryReader reader = new BinaryReader(resourceStream))
										{
											// read file in chunks in order to reduce memory consumption and increase performance
											while (readCount < length)
											{
												int actual = reader.Read(buffer, 0, buffer.Length);
												readCount += actual;
												writer.Write(buffer, 0, actual);
											}
										}
									}
								}
							}
							created = true;
						}
						else
						{
							this.CreateDatabase();
							created = true;
						}
					}
				}
				else
				{
					this.CreateDatabase();
					created = true;
				}
			}
			return created;
		}
		
		public bool LogDebug
		{
			set
			{
				if (value)
				{
					this.Log = new DebugWriter();
				}
			}
		}
		
		public static string ConnectionString = "Data Source=isostore:/DBSoal.sdf";

		public static string ConnectionStringReadOnly = "Data Source=appdata:/DBSoal.sdf;File Mode=Read Only;";

		public static string FileName = "DBSoal.sdf";

		public DBSoalContext(string connectionString) : base(connectionString)
		{
			OnCreated();
		}
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSoalKepribadian(SoalKepribadian instance);
    partial void UpdateSoalKepribadian(SoalKepribadian instance);
    partial void DeleteSoalKepribadian(SoalKepribadian instance);
    partial void InsertSoalPsikotes(SoalPsikotes instance);
    partial void UpdateSoalPsikotes(SoalPsikotes instance);
    partial void DeleteSoalPsikotes(SoalPsikotes instance);
    #endregion
		
		public System.Data.Linq.Table<SoalKepribadian> SoalKepribadian
		{
			get
			{
				return this.GetTable<SoalKepribadian>();
			}
		}
		
		public System.Data.Linq.Table<SoalPsikotes> SoalPsikotes
		{
			get
			{
				return this.GetTable<SoalPsikotes>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class SoalKepribadian : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Kode_Soal;
		
		private string _JawabanA;
		
		private string _JawabanB;
		
		private string _JawabanC;
		
		private string _JawabanD;
		
		private string _Jenis_Soal;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKode_SoalChanging(string value);
    partial void OnKode_SoalChanged();
    partial void OnJawabanAChanging(string value);
    partial void OnJawabanAChanged();
    partial void OnJawabanBChanging(string value);
    partial void OnJawabanBChanged();
    partial void OnJawabanCChanging(string value);
    partial void OnJawabanCChanged();
    partial void OnJawabanDChanging(string value);
    partial void OnJawabanDChanged();
    partial void OnJenis_SoalChanging(string value);
    partial void OnJenis_SoalChanged();
    #endregion
		
		public SoalKepribadian()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kode_Soal", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Kode_Soal
		{
			get
			{
				return this._Kode_Soal;
			}
			set
			{
				if ((this._Kode_Soal != value))
				{
					this.OnKode_SoalChanging(value);
					this.SendPropertyChanging();
					this._Kode_Soal = value;
					this.SendPropertyChanged("Kode_Soal");
					this.OnKode_SoalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JawabanA", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string JawabanA
		{
			get
			{
				return this._JawabanA;
			}
			set
			{
				if ((this._JawabanA != value))
				{
					this.OnJawabanAChanging(value);
					this.SendPropertyChanging();
					this._JawabanA = value;
					this.SendPropertyChanged("JawabanA");
					this.OnJawabanAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JawabanB", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string JawabanB
		{
			get
			{
				return this._JawabanB;
			}
			set
			{
				if ((this._JawabanB != value))
				{
					this.OnJawabanBChanging(value);
					this.SendPropertyChanging();
					this._JawabanB = value;
					this.SendPropertyChanged("JawabanB");
					this.OnJawabanBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JawabanC", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string JawabanC
		{
			get
			{
				return this._JawabanC;
			}
			set
			{
				if ((this._JawabanC != value))
				{
					this.OnJawabanCChanging(value);
					this.SendPropertyChanging();
					this._JawabanC = value;
					this.SendPropertyChanged("JawabanC");
					this.OnJawabanCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JawabanD", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string JawabanD
		{
			get
			{
				return this._JawabanD;
			}
			set
			{
				if ((this._JawabanD != value))
				{
					this.OnJawabanDChanging(value);
					this.SendPropertyChanging();
					this._JawabanD = value;
					this.SendPropertyChanged("JawabanD");
					this.OnJawabanDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jenis_Soal", DbType="NVarChar(300)")]
		public string Jenis_Soal
		{
			get
			{
				return this._Jenis_Soal;
			}
			set
			{
				if ((this._Jenis_Soal != value))
				{
					this.OnJenis_SoalChanging(value);
					this.SendPropertyChanging();
					this._Jenis_Soal = value;
					this.SendPropertyChanged("Jenis_Soal");
					this.OnJenis_SoalChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class SoalPsikotes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Kode_Soal;
		
		private string _Jenis_Soal;
		
		private string _Isi_Soal;
		
		private string _JawabanA;
		
		private string _JawabanB;
		
		private string _JawabanC;
		
		private string _JawabanD;
		
		private string _JawabanBenar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKode_SoalChanging(string value);
    partial void OnKode_SoalChanged();
    partial void OnJenis_SoalChanging(string value);
    partial void OnJenis_SoalChanged();
    partial void OnIsi_SoalChanging(string value);
    partial void OnIsi_SoalChanged();
    partial void OnJawabanAChanging(string value);
    partial void OnJawabanAChanged();
    partial void OnJawabanBChanging(string value);
    partial void OnJawabanBChanged();
    partial void OnJawabanCChanging(string value);
    partial void OnJawabanCChanged();
    partial void OnJawabanDChanging(string value);
    partial void OnJawabanDChanged();
    partial void OnJawabanBenarChanging(string value);
    partial void OnJawabanBenarChanged();
    #endregion
		
		public SoalPsikotes()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kode_Soal", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Kode_Soal
		{
			get
			{
				return this._Kode_Soal;
			}
			set
			{
				if ((this._Kode_Soal != value))
				{
					this.OnKode_SoalChanging(value);
					this.SendPropertyChanging();
					this._Kode_Soal = value;
					this.SendPropertyChanged("Kode_Soal");
					this.OnKode_SoalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jenis_Soal", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Jenis_Soal
		{
			get
			{
				return this._Jenis_Soal;
			}
			set
			{
				if ((this._Jenis_Soal != value))
				{
					this.OnJenis_SoalChanging(value);
					this.SendPropertyChanging();
					this._Jenis_Soal = value;
					this.SendPropertyChanged("Jenis_Soal");
					this.OnJenis_SoalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Isi_Soal", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string Isi_Soal
		{
			get
			{
				return this._Isi_Soal;
			}
			set
			{
				if ((this._Isi_Soal != value))
				{
					this.OnIsi_SoalChanging(value);
					this.SendPropertyChanging();
					this._Isi_Soal = value;
					this.SendPropertyChanged("Isi_Soal");
					this.OnIsi_SoalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JawabanA", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string JawabanA
		{
			get
			{
				return this._JawabanA;
			}
			set
			{
				if ((this._JawabanA != value))
				{
					this.OnJawabanAChanging(value);
					this.SendPropertyChanging();
					this._JawabanA = value;
					this.SendPropertyChanged("JawabanA");
					this.OnJawabanAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JawabanB", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string JawabanB
		{
			get
			{
				return this._JawabanB;
			}
			set
			{
				if ((this._JawabanB != value))
				{
					this.OnJawabanBChanging(value);
					this.SendPropertyChanging();
					this._JawabanB = value;
					this.SendPropertyChanged("JawabanB");
					this.OnJawabanBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JawabanC", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string JawabanC
		{
			get
			{
				return this._JawabanC;
			}
			set
			{
				if ((this._JawabanC != value))
				{
					this.OnJawabanCChanging(value);
					this.SendPropertyChanging();
					this._JawabanC = value;
					this.SendPropertyChanged("JawabanC");
					this.OnJawabanCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JawabanD", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string JawabanD
		{
			get
			{
				return this._JawabanD;
			}
			set
			{
				if ((this._JawabanD != value))
				{
					this.OnJawabanDChanging(value);
					this.SendPropertyChanging();
					this._JawabanD = value;
					this.SendPropertyChanged("JawabanD");
					this.OnJawabanDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JawabanBenar", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string JawabanBenar
		{
			get
			{
				return this._JawabanBenar;
			}
			set
			{
				if ((this._JawabanBenar != value))
				{
					this.OnJawabanBenarChanging(value);
					this.SendPropertyChanging();
					this._JawabanBenar = value;
					this.SendPropertyChanged("JawabanBenar");
					this.OnJawabanBenarChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
